CREATE TABLE paises (`id` bigint(20) NOT NULL AUTO_INCREMENT,`codigo` bigint(20) NOT NULL,`dataregistro` datetime DEFAULT NULL,`username` varchar(20) DEFAULT NULL, , `nome` varchar(50) DEFAULT NULL, PRIMARY KEY(`id`),) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = latin1;
INSERT INTO paises (ID, codigo, nome)VALUES (013, 013, "AFEGANISTAO");
INSERT INTO paises (ID, codigo, nome)VALUES (017, 017, "ALBANIA, REPUBLICA  DA");
INSERT INTO paises (ID, codigo, nome)VALUES (023, 023, "ALEMANHA");
INSERT INTO paises (ID, codigo, nome)VALUES (031, 031, "BURKINA FASO");
INSERT INTO paises (ID, codigo, nome)VALUES (037, 037, "ANDORRA");
INSERT INTO paises (ID, codigo, nome)VALUES (040, 040, "ANGOLA");
INSERT INTO paises (ID, codigo, nome)VALUES (041, 041, "ANGUILLA");
INSERT INTO paises (ID, codigo, nome)VALUES (043, 043, "ANTIGUA E BARBUDA");
INSERT INTO paises (ID, codigo, nome)VALUES (047, 047, "ANTILHAS HOLANDESAS");
INSERT INTO paises (ID, codigo, nome)VALUES (053, 053, "ARABIA SAUDITA");
INSERT INTO paises (ID, codigo, nome)VALUES (059, 059, "ARGELIA");
INSERT INTO paises (ID, codigo, nome)VALUES (063, 063, "ARGENTINA");
INSERT INTO paises (ID, codigo, nome)VALUES (064, 064, "ARMENIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (065, 065, "ARUBA");
INSERT INTO paises (ID, codigo, nome)VALUES (069, 069, "AUSTRALIA");
INSERT INTO paises (ID, codigo, nome)VALUES (072, 072, "AUSTRIA");
INSERT INTO paises (ID, codigo, nome)VALUES (073, 073, "AZERBAIJAO, REPUBLICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (077, 077, "BAHAMAS, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (080, 080, "BAHREIN, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (081, 081, "BANGLADESH");
INSERT INTO paises (ID, codigo, nome)VALUES (083, 083, "BARBADOS");
INSERT INTO paises (ID, codigo, nome)VALUES (085, 085, "BELARUS, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (087, 087, "BELGICA");
INSERT INTO paises (ID, codigo, nome)VALUES (088, 088, "BELIZE");
INSERT INTO paises (ID, codigo, nome)VALUES (090, 090, "BERMUDAS");
INSERT INTO paises (ID, codigo, nome)VALUES (093, 093, "MIANMAR (BIRMANIA)");
INSERT INTO paises (ID, codigo, nome)VALUES (097, 097, "BOLIVIA, ESTADO PLURINACIONAL DA");
INSERT INTO paises (ID, codigo, nome)VALUES (098, 098, "BOSNIA - HERZEGOVINA (REPUBLICA DA)");
INSERT INTO paises (ID, codigo, nome)VALUES (101, 101, "BOTSUANA");
INSERT INTO paises (ID, codigo, nome)VALUES (105, 105, "BRASIL");
INSERT INTO paises (ID, codigo, nome)VALUES (108, 108, "BRUNEI");
INSERT INTO paises (ID, codigo, nome)VALUES (111, 111, "BULGARIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (115, 115, "BURUNDI");
INSERT INTO paises (ID, codigo, nome)VALUES (119, 119, "BUTAO");
INSERT INTO paises (ID, codigo, nome)VALUES (127, 127, "CABO VERDE, REPUBLICA DE");
INSERT INTO paises (ID, codigo, nome)VALUES (137, 137, "CAYMAN, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (141, 141, "CAMBOJA");
INSERT INTO paises (ID, codigo, nome)VALUES (145, 145, "CAMAROES");
INSERT INTO paises (ID, codigo, nome)VALUES (149, 149, "CANADA");
INSERT INTO paises (ID, codigo, nome)VALUES (150, 150, "JERSEY, ILHA DO CANAL");
INSERT INTO paises (ID, codigo, nome)VALUES (151, 151, "CANARIAS, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (153, 153, "CAZAQUISTAO, REPUBLICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (154, 154, "CATAR");
INSERT INTO paises (ID, codigo, nome)VALUES (158, 158, "CHILE");
INSERT INTO paises (ID, codigo, nome)VALUES (160, 160, "CHINA, REPUBLICA POPULAR");
INSERT INTO paises (ID, codigo, nome)VALUES (161, 161, "FORMOSA (TAIWAN)");
INSERT INTO paises (ID, codigo, nome)VALUES (163, 163, "CHIPRE");
INSERT INTO paises (ID, codigo, nome)VALUES (165, 165, "COCOS(KEELING),ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (169, 169, "COLOMBIA");
INSERT INTO paises (ID, codigo, nome)VALUES (173, 173, "COMORES, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (177, 177, "CONGO");
INSERT INTO paises (ID, codigo, nome)VALUES (183, 183, "COOK, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (187, 187, "COREIA (DO NORTE), REP.POP.DEMOCRATICA");
INSERT INTO paises (ID, codigo, nome)VALUES (190, 190, "COREIA (DO SUL), REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (193, 193, "COSTA DO MARFIM");
INSERT INTO paises (ID, codigo, nome)VALUES (195, 195, "CROACIA (REPUBLICA DA)");
INSERT INTO paises (ID, codigo, nome)VALUES (196, 196, "COSTA RICA");
INSERT INTO paises (ID, codigo, nome)VALUES (198, 198, "COVEITE");
INSERT INTO paises (ID, codigo, nome)VALUES (199, 199, "CUBA");
INSERT INTO paises (ID, codigo, nome)VALUES (229, 229, "BENIN");
INSERT INTO paises (ID, codigo, nome)VALUES (232, 232, "DINAMARCA");
INSERT INTO paises (ID, codigo, nome)VALUES (235, 235, "DOMINICA,ILHA");
INSERT INTO paises (ID, codigo, nome)VALUES (239, 239, "EQUADOR");
INSERT INTO paises (ID, codigo, nome)VALUES (240, 240, "EGITO");
INSERT INTO paises (ID, codigo, nome)VALUES (243, 243, "ERITREIA");
INSERT INTO paises (ID, codigo, nome)VALUES (244, 244, "EMIRADOS ARABES UNIDOS");
INSERT INTO paises (ID, codigo, nome)VALUES (245, 245, "ESPANHA");
INSERT INTO paises (ID, codigo, nome)VALUES (246, 246, "ESLOVENIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (247, 247, "ESLOVACA, REPUBLICA");
INSERT INTO paises (ID, codigo, nome)VALUES (249, 249, "ESTADOS UNIDOS");
INSERT INTO paises (ID, codigo, nome)VALUES (251, 251, "ESTONIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (253, 253, "ETIOPIA");
INSERT INTO paises (ID, codigo, nome)VALUES (255, 255, "FALKLAND (ILHAS MALVINAS)");
INSERT INTO paises (ID, codigo, nome)VALUES (259, 259, "FEROE, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (267, 267, "FILIPINAS");
INSERT INTO paises (ID, codigo, nome)VALUES (271, 271, "FINLANDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (275, 275, "FRANCA");
INSERT INTO paises (ID, codigo, nome)VALUES (281, 281, "GABAO");
INSERT INTO paises (ID, codigo, nome)VALUES (285, 285, "GAMBIA");
INSERT INTO paises (ID, codigo, nome)VALUES (289, 289, "GANA");
INSERT INTO paises (ID, codigo, nome)VALUES (291, 291, "GEORGIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (293, 293, "GIBRALTAR");
INSERT INTO paises (ID, codigo, nome)VALUES (297, 297, "GRANADA");
INSERT INTO paises (ID, codigo, nome)VALUES (301, 301, "GRECIA");
INSERT INTO paises (ID, codigo, nome)VALUES (305, 305, "GROENLANDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (309, 309, "GUADALUPE");
INSERT INTO paises (ID, codigo, nome)VALUES (313, 313, "GUAM");
INSERT INTO paises (ID, codigo, nome)VALUES (317, 317, "GUATEMALA");
INSERT INTO paises (ID, codigo, nome)VALUES (325, 325, "GUIANA FRANCESA");
INSERT INTO paises (ID, codigo, nome)VALUES (329, 329, "GUINE");
INSERT INTO paises (ID, codigo, nome)VALUES (331, 331, "GUINE-EQUATORIAL");
INSERT INTO paises (ID, codigo, nome)VALUES (334, 334, "GUINE-BISSAU");
INSERT INTO paises (ID, codigo, nome)VALUES (337, 337, "GUIANA");
INSERT INTO paises (ID, codigo, nome)VALUES (341, 341, "HAITI");
INSERT INTO paises (ID, codigo, nome)VALUES (345, 345, "HONDURAS");
INSERT INTO paises (ID, codigo, nome)VALUES (351, 351, "HONG KONG");
INSERT INTO paises (ID, codigo, nome)VALUES (355, 355, "HUNGRIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (357, 357, "IEMEN");
INSERT INTO paises (ID, codigo, nome)VALUES (359, 359, "MAN, ILHA DE");
INSERT INTO paises (ID, codigo, nome)VALUES (361, 361, "INDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (365, 365, "INDONESIA");
INSERT INTO paises (ID, codigo, nome)VALUES (369, 369, "IRAQUE");
INSERT INTO paises (ID, codigo, nome)VALUES (372, 372, "IRA, REPUBLICA ISLAMICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (375, 375, "IRLANDA");
INSERT INTO paises (ID, codigo, nome)VALUES (379, 379, "ISLANDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (383, 383, "ISRAEL");
INSERT INTO paises (ID, codigo, nome)VALUES (386, 386, "ITALIA");
INSERT INTO paises (ID, codigo, nome)VALUES (391, 391, "JAMAICA");
INSERT INTO paises (ID, codigo, nome)VALUES (396, 396, "JOHNSTON, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (399, 399, "JAPAO");
INSERT INTO paises (ID, codigo, nome)VALUES (403, 403, "JORDANIA");
INSERT INTO paises (ID, codigo, nome)VALUES (411, 411, "KIRIBATI");
INSERT INTO paises (ID, codigo, nome)VALUES (420, 420, "LAOS, REP.POP.DEMOCR.DO");
INSERT INTO paises (ID, codigo, nome)VALUES (423, 423, "LEBUAN,ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (426, 426, "LESOTO");
INSERT INTO paises (ID, codigo, nome)VALUES (427, 427, "LETONIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (431, 431, "LIBANO");
INSERT INTO paises (ID, codigo, nome)VALUES (434, 434, "LIBERIA");
INSERT INTO paises (ID, codigo, nome)VALUES (438, 438, "LIBIA");
INSERT INTO paises (ID, codigo, nome)VALUES (440, 440, "LIECHTENSTEIN");
INSERT INTO paises (ID, codigo, nome)VALUES (442, 442, "LITUANIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (445, 445, "LUXEMBURGO");
INSERT INTO paises (ID, codigo, nome)VALUES (447, 447, "MACAU");
INSERT INTO paises (ID, codigo, nome)VALUES (449, 449, "MACEDONIA, ANT.REP.IUGOSLAVA");
INSERT INTO paises (ID, codigo, nome)VALUES (450, 450, "MADAGASCAR");
INSERT INTO paises (ID, codigo, nome)VALUES (452, 452, "ILHA DA MADEIRA");
INSERT INTO paises (ID, codigo, nome)VALUES (455, 455, "MALASIA");
INSERT INTO paises (ID, codigo, nome)VALUES (458, 458, "MALAVI");
INSERT INTO paises (ID, codigo, nome)VALUES (461, 461, "MALDIVAS");
INSERT INTO paises (ID, codigo, nome)VALUES (464, 464, "MALI");
INSERT INTO paises (ID, codigo, nome)VALUES (467, 467, "MALTA");
INSERT INTO paises (ID, codigo, nome)VALUES (472, 472, "MARIANAS DO NORTE");
INSERT INTO paises (ID, codigo, nome)VALUES (474, 474, "MARROCOS");
INSERT INTO paises (ID, codigo, nome)VALUES (476, 476, "MARSHALL,ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (477, 477, "MARTINICA");
INSERT INTO paises (ID, codigo, nome)VALUES (485, 485, "MAURICIO");
INSERT INTO paises (ID, codigo, nome)VALUES (488, 488, "MAURITANIA");
INSERT INTO paises (ID, codigo, nome)VALUES (490, 490, "MIDWAY, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (493, 493, "MEXICO");
INSERT INTO paises (ID, codigo, nome)VALUES (494, 494, "MOLDAVIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (495, 495, "MONACO");
INSERT INTO paises (ID, codigo, nome)VALUES (497, 497, "MONGOLIA");
INSERT INTO paises (ID, codigo, nome)VALUES (498, 498, "MONTENEGRO");
INSERT INTO paises (ID, codigo, nome)VALUES (499, 499, "MICRONESIA");
INSERT INTO paises (ID, codigo, nome)VALUES (501, 501, "MONTSERRAT,ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (505, 505, "MOCAMBIQUE");
INSERT INTO paises (ID, codigo, nome)VALUES (507, 507, "NAMIBIA");
INSERT INTO paises (ID, codigo, nome)VALUES (508, 508, "NAURU");
INSERT INTO paises (ID, codigo, nome)VALUES (511, 511, "CHRISTMAS,ILHA (NAVIDAD)");
INSERT INTO paises (ID, codigo, nome)VALUES (517, 517, "NEPAL");
INSERT INTO paises (ID, codigo, nome)VALUES (521, 521, "NICARAGUA");
INSERT INTO paises (ID, codigo, nome)VALUES (525, 525, "NIGER");
INSERT INTO paises (ID, codigo, nome)VALUES (528, 528, "NIGERIA");
INSERT INTO paises (ID, codigo, nome)VALUES (531, 531, "NIUE,ILHA");
INSERT INTO paises (ID, codigo, nome)VALUES (535, 535, "NORFOLK,ILHA");
INSERT INTO paises (ID, codigo, nome)VALUES (538, 538, "NORUEGA");
INSERT INTO paises (ID, codigo, nome)VALUES (542, 542, "NOVA CALEDONIA");
INSERT INTO paises (ID, codigo, nome)VALUES (545, 545, "PAPUA NOVA GUINE");
INSERT INTO paises (ID, codigo, nome)VALUES (548, 548, "NOVA ZELANDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (551, 551, "VANUATU");
INSERT INTO paises (ID, codigo, nome)VALUES (556, 556, "OMA");
INSERT INTO paises (ID, codigo, nome)VALUES (566, 566, "PACIFICO,ILHAS DO (POSSESSAO DOS EUA)");
INSERT INTO paises (ID, codigo, nome)VALUES (573, 573, "PAISES BAIXOS (HOLANDA)");
INSERT INTO paises (ID, codigo, nome)VALUES (575, 575, "PALAU");
INSERT INTO paises (ID, codigo, nome)VALUES (576, 576, "PAQUISTAO");
INSERT INTO paises (ID, codigo, nome)VALUES (578, 578, "PALESTINA");
INSERT INTO paises (ID, codigo, nome)VALUES (580, 580, "PANAMA");
INSERT INTO paises (ID, codigo, nome)VALUES (586, 586, "PARAGUAI");
INSERT INTO paises (ID, codigo, nome)VALUES (589, 589, "PERU");
INSERT INTO paises (ID, codigo, nome)VALUES (593, 593, "PITCAIRN,ILHA");
INSERT INTO paises (ID, codigo, nome)VALUES (599, 599, "POLINESIA FRANCESA");
INSERT INTO paises (ID, codigo, nome)VALUES (603, 603, "POLONIA, REPUBLICA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (607, 607, "PORTUGAL");
INSERT INTO paises (ID, codigo, nome)VALUES (611, 611, "PORTO RICO");
INSERT INTO paises (ID, codigo, nome)VALUES (623, 623, "QUENIA");
INSERT INTO paises (ID, codigo, nome)VALUES (625, 625, "QUIRGUIZ, REPUBLICA");
INSERT INTO paises (ID, codigo, nome)VALUES (628, 628, "REINO UNIDO");
INSERT INTO paises (ID, codigo, nome)VALUES (640, 640, "REPUBLICA CENTRO-AFRICANA");
INSERT INTO paises (ID, codigo, nome)VALUES (647, 647, "REPUBLICA DOMINICANA");
INSERT INTO paises (ID, codigo, nome)VALUES (660, 660, "REUNIAO, ILHA");
INSERT INTO paises (ID, codigo, nome)VALUES (665, 665, "ZIMBABUE");
INSERT INTO paises (ID, codigo, nome)VALUES (670, 670, "ROMENIA");
INSERT INTO paises (ID, codigo, nome)VALUES (675, 675, "RUANDA");
INSERT INTO paises (ID, codigo, nome)VALUES (676, 676, "RUSSIA, FEDERACAO DA");
INSERT INTO paises (ID, codigo, nome)VALUES (677, 677, "SALOMAO, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (685, 685, "SAARA OCIDENTAL");
INSERT INTO paises (ID, codigo, nome)VALUES (687, 687, "EL SALVADOR");
INSERT INTO paises (ID, codigo, nome)VALUES (690, 690, "SAMOA");
INSERT INTO paises (ID, codigo, nome)VALUES (691, 691, "SAMOA AMERICANA");
INSERT INTO paises (ID, codigo, nome)VALUES (695, 695, "SAO CRISTOVAO E NEVES,ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (697, 697, "SAN MARINO");
INSERT INTO paises (ID, codigo, nome)VALUES (700, 700, "SAO PEDRO E MIQUELON");
INSERT INTO paises (ID, codigo, nome)VALUES (705, 705, "SAO VICENTE E GRANADINAS");
INSERT INTO paises (ID, codigo, nome)VALUES (710, 710, "SANTA HELENA");
INSERT INTO paises (ID, codigo, nome)VALUES (715, 715, "SANTA LUCIA");
INSERT INTO paises (ID, codigo, nome)VALUES (720, 720, "SAO TOME E PRINCIPE, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (728, 728, "SENEGAL");
INSERT INTO paises (ID, codigo, nome)VALUES (731, 731, "SEYCHELLES");
INSERT INTO paises (ID, codigo, nome)VALUES (735, 735, "SERRA LEOA");
INSERT INTO paises (ID, codigo, nome)VALUES (737, 737, "SERVIA");
INSERT INTO paises (ID, codigo, nome)VALUES (741, 741, "CINGAPURA");
INSERT INTO paises (ID, codigo, nome)VALUES (744, 744, "SIRIA, REPUBLICA ARABE DA");
INSERT INTO paises (ID, codigo, nome)VALUES (748, 748, "SOMALIA");
INSERT INTO paises (ID, codigo, nome)VALUES (750, 750, "SRI LANKA");
INSERT INTO paises (ID, codigo, nome)VALUES (754, 754, "SUAZILANDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (756, 756, "AFRICA DO SUL");
INSERT INTO paises (ID, codigo, nome)VALUES (759, 759, "SUDAO");
INSERT INTO paises (ID, codigo, nome)VALUES (764, 764, "SUECIA");
INSERT INTO paises (ID, codigo, nome)VALUES (767, 767, "SUICA");
INSERT INTO paises (ID, codigo, nome)VALUES (770, 770, "SURINAME");
INSERT INTO paises (ID, codigo, nome)VALUES (772, 772, "TADJIQUISTAO, REPUBLICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (776, 776, "TAILANDIA");
INSERT INTO paises (ID, codigo, nome)VALUES (780, 780, "TANZANIA, REP.UNIDA DA");
INSERT INTO paises (ID, codigo, nome)VALUES (782, 782, "TERRITORIO BRIT.OC.INDICO");
INSERT INTO paises (ID, codigo, nome)VALUES (783, 783, "DJIBUTI");
INSERT INTO paises (ID, codigo, nome)VALUES (788, 788, "CHADE");
INSERT INTO paises (ID, codigo, nome)VALUES (791, 791, "TCHECA, REPUBLICA");
INSERT INTO paises (ID, codigo, nome)VALUES (795, 795, "TIMOR LESTE");
INSERT INTO paises (ID, codigo, nome)VALUES (800, 800, "TOGO");
INSERT INTO paises (ID, codigo, nome)VALUES (805, 805, "TOQUELAU,ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (810, 810, "TONGA");
INSERT INTO paises (ID, codigo, nome)VALUES (815, 815, "TRINIDAD E TOBAGO");
INSERT INTO paises (ID, codigo, nome)VALUES (820, 820, "TUNISIA");
INSERT INTO paises (ID, codigo, nome)VALUES (823, 823, "TURCAS E CAICOS,ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (824, 824, "TURCOMENISTAO, REPUBLICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (827, 827, "TURQUIA");
INSERT INTO paises (ID, codigo, nome)VALUES (828, 828, "TUVALU");
INSERT INTO paises (ID, codigo, nome)VALUES (831, 831, "UCRANIA");
INSERT INTO paises (ID, codigo, nome)VALUES (833, 833, "UGANDA");
INSERT INTO paises (ID, codigo, nome)VALUES (845, 845, "URUGUAI");
INSERT INTO paises (ID, codigo, nome)VALUES (847, 847, "UZBEQUISTAO, REPUBLICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (848, 848, "VATICANO, EST.DA CIDADE DO");
INSERT INTO paises (ID, codigo, nome)VALUES (850, 850, "VENEZUELA");
INSERT INTO paises (ID, codigo, nome)VALUES (858, 858, "VIETNA");
INSERT INTO paises (ID, codigo, nome)VALUES (863, 863, "VIRGENS,ILHAS (BRITANICAS)");
INSERT INTO paises (ID, codigo, nome)VALUES (866, 866, "VIRGENS,ILHAS (E.U.A.)");
INSERT INTO paises (ID, codigo, nome)VALUES (870, 870, "FIJI");
INSERT INTO paises (ID, codigo, nome)VALUES (873, 873, "WAKE, ILHA");
INSERT INTO paises (ID, codigo, nome)VALUES (875, 875, "WALLIS E FUTUNA, ILHAS");
INSERT INTO paises (ID, codigo, nome)VALUES (888, 888, "CONGO, REPUBLICA DEMOCRATICA DO");
INSERT INTO paises (ID, codigo, nome)VALUES (890, 890, "ZAMBIA");
INSERT INTO paises (ID, codigo, nome)VALUES (990, 990, "PROVISAO DE NAVIOS E AERONAVES");
INSERT INTO paises (ID, codigo, nome)VALUES (994, 994, "A DESIGNAR");
INSERT INTO paises (ID, codigo, nome)VALUES (995, 995, "BANCOS CENTRAIS");
INSERT INTO paises (ID, codigo, nome)VALUES (997, 997, "ORGANIZACOES INTERNACIONAIS");
